### ISSUE TITLE
License and release

### ISSUE THREAD

**Issue by igoraj** [lukehinds/puppet-aide#2]
Hi @lukehinds,
I was wondering about the license used on this project. On [metadata.json](https://github.com/lukehinds/puppet-aide/blob/master/metadata.json#L6) there is reference to Apache License 2.0 but there is no LICENSE file commited in the repository?
In addition if it is not too much trouble could you create git tag/github release for the same version as it is on Forge (1.0.3)?

**Comment by lukehinds** [comment]
Hi @igoraj 

Hope this is what you need:

https://github.com/lukehinds/puppet-aide/releases/tag/1.0.3

https://github.com/lukehinds/puppet-aide/blob/master/LICENSE

Let me know if anything else, or feel free to make pull requests. Hope the module is useful to you!

Please ack I can close this, if it resolves what is needed.

**Comment by igoraj** [comment]
Hey @lukehinds 

this is exactly what I was asking for, many thanks!

We'll see how it goes, if we will do some changes for sure we'll open a PR but otherwise thank you for all the work you have done with this module!

Cheers
